
/* fi le generated by qcc, do not modify */

typedef struct
{
	short	qcc_self;
	short	qcc_other;
	short	qcc_world;
	float	qcc_time;
	float	qcc_frametime;
	float	qcc_force_retouch;
	string_t	qcc_mapname;
	float	qcc_deathmatch;
	float	qcc_coop;
	float	qcc_teamplay;
	float	qcc_serverflags;
	float	qcc_total_secrets;
	float	qcc_total_monsters;
	float	qcc_found_secrets;
	float	qcc_killed_monsters;
	float	qcc_parm1;
	float	qcc_parm2;
	float	qcc_parm3;
	float	qcc_parm4;
	float	qcc_parm5;
	float	qcc_parm6;
	float	qcc_parm7;
	float	qcc_parm8;
	float	qcc_parm9;
	float	qcc_parm10;
	float	qcc_parm11;
	float	qcc_parm12;
	float	qcc_parm13;
	float	qcc_parm14;
	float	qcc_parm15;
	float	qcc_parm16;
	vector	qcc_v_forward;
	vector	qcc_v_up;
	vector	qcc_v_right;
	float	qcc_trace_allsolid;
	float	qcc_trace_startsolid;
	float	qcc_trace_fraction;
	vector	qcc_trace_endpos;
	vector	qcc_trace_plane_normal;
	float	qcc_trace_plane_dist;
	short	qcc_trace_ent;
	float	qcc_trace_inopen;
	float	qcc_trace_inwater;
	short	qcc_msg_entity;
	string_t	qcc_end_sys_globals;
	float	qcc_movedist;
	float	qcc_gameover;
	string_t	qcc_string_null;
	float	qcc_empty_float;
	short	qcc_newmis;
	short	qcc_activator;
	short	qcc_damage_attacker;
	float	qcc_framecount;
	float	qcc_skill;
	float	qcc_enemy_vis;
	float	qcc_enemy_infront;
	float	qcc_enemy_range;
	float	qcc_enemy_yaw;
	float	qcc_current_yaw;
	short	qcc_sight_entity;
	float	qcc_sight_entity_time;
	short	qcc_multi_ent;
	float	qcc_multi_damage;
	short	qcc_lastspawn;
	short	qcc_bodyque_head;
	float	qcc_modelindex_eyes;
	float	qcc_modelindex_player;
	float	qcc_intermission_running;
	float	qcc_intermission_exittime;
	string_t	qcc_nextmap;
	short	qcc_stemp;
	short	qcc_otemp;
	short	qcc_s;
	short	qcc_old;
	short	qcc_le1;
	short	qcc_le2;
	float	qcc_lightning_end;
	float	qcc_hknight_type;
	short	qcc_shub;
} progsvars_t;

extern progsvars_t progs;
